WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.mxgraph.confluence.plugins.diagramly:drawio-reader', location = 'js/theming.js' */
try{window.mxConfThemeObserver=function(f,d,c){function g(b){var a=document.documentElement.getAttribute("data-color-mode");return a?"dark"===a:b?null:!1}function e(b){clearTimeout(m);var a=Date.now();1E3<a-h&&(h=a,f(b,d))}var h=0,m=setTimeout(function(){e(!1)},200);const n=new MutationObserver(function(b,a){for(const k of b)if("attributes"===k.type&&"data-color-mode"===k.attributeName&&(e(g()),c)){a.disconnect();break}});var l=g(!0);if(null!=l&&(e(l),c))return;n.observe(document.documentElement,
{attributes:!0})}}catch(f){window.mxConfThemeObserver=function(d,c){d(!1,c)}};
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.mxgraph.confluence.plugins.diagramly:drawio-reader', location = 'js/mxInit.js' */
window.ATLAS_RESOURCE_BASE="undefined"!==typeof DrawioProperties&&null!=DrawioProperties.drawioResourceRoot?DrawioProperties.drawioResourceRoot:AJS.contextPath()+"/download/resources/com.mxgraph.confluence.plugins.diagramly:drawio-editor";window.RESOURCES_PATH=ATLAS_RESOURCE_BASE+"/resources";window.RESOURCE_BASE=RESOURCES_PATH+"/dia";window.STENCIL_PATH=ATLAS_RESOURCE_BASE+"/stencils";window.SHAPES_PATH=ATLAS_RESOURCE_BASE+"/shapes";window.IMAGE_PATH=ATLAS_RESOURCE_BASE+"/images";
window.GRAPH_IMAGE_PATH="/img";window.STYLE_PATH=ATLAS_RESOURCE_BASE+"/styles";window.CSS_PATH=STYLE_PATH;window.OPEN_FORM=ATLAS_RESOURCE_BASE+"/html/open.html";window.TEMPLATE_PATH=ATLAS_RESOURCE_BASE+"/templates";window.PROXY_URL=("undefined"!==typeof DrawioProperties?DrawioProperties.contextPath:AJS.contextPath())+"/plugins/servlet/drawio-proxyServlet";window.SVGLOADER_URL=("undefined"!==typeof DrawioProperties?DrawioProperties.contextPath:AJS.contextPath())+"/plugins/servlet/drawio-svgServlet";
window.mxBasePath=ATLAS_RESOURCE_BASE+"/mxgraph";window.mxImageBasePath=window.mxBasePath+"/images";window.mxLoadStylesheets=!1;window.mxLoadResources=!1;window.mxLoadSettings=!1;window.isSvgBrowser=0>navigator.userAgent.indexOf("MSIE")||9<=document.documentMode;window.DRAWIO_VIEWER_URL=window.location.protocol+"//"+window.location.host+("undefined"!==typeof DrawioProperties?DrawioProperties.contextPath:AJS.contextPath())+"/download/resources/com.mxgraph.confluence.plugins.diagramly:drawio-reader/js/viewer-static.min.js";
window.VIEWER_URL=window.DRAWIO_VIEWER_URL;window.DRAW_MATH_URL=ATLAS_RESOURCE_BASE+"/math/es5";window.MXGRAPH=window.MXGRAPH||{};MXGRAPH.viewerContainer=null;MXGRAPH.readerOpts=null;var isLocalStorage=!1,mxIsElectron=!1;try{isLocalStorage="undefined"!=typeof localStorage}catch(b){}
(function(){if(!window.mxCssInjected)try{window.mxCssInjected=!0;var b=document.createElement("style");b.type="text/css";b.innerHTML=".geDiagramContainer blockquote,\n.drawio-macro blockquote {\ncolor: #000 !important;\nmargin:1em 40px 1em 40px !important;\npadding: 0px !important;\nborder-style: none;\n}\nhtml body .geDiagramContainer ul, html body .geDiagramContainer ol,\nhtml body .drawio-macro ul, html body .drawio-macro ol {\nmargin:1em 0px 1em 0px;\npadding-left: 40px;\n}\n.geDiagramContainer h1,\n.drawio-macro h1 {\ncolor: #000 !important;\nfont-size: 2em;\nfont-weight: bold !important;\nline-height: inherit !important;\nmargin:0.67em 0px 0.67em 0px !important;\n}\n.geDiagramContainer h2,\n.drawio-macro h2 {\ncolor: #000 !important;\nfont-size: 1.5em !important;\nfont-weight: bold !important;\nline-height: inherit !important;\nmargin:0.83em 0px 0.83em 0px !important;\n}\n.geDiagramContainer h3,\n.drawio-macro h3 {\ncolor: #000 !important;\nfont-size: 1.17em !important;\nfont-weight: bold !important;\nline-height: inherit !important;\nmargin:1em 0px 1em 0px !important;\n}\n.geDiagramContainer h4,\n.drawio-macro h4 {\ncolor: #000 !important;\nfont-size: 1em !important;\nfont-weight: bold !important;\nline-height: inherit !important;\nmargin:1.33em 0px 1.33em 0px !important;\n}\n.geDiagramContainer h5,\n.drawio-macro h5 {\ncolor: #000 !important;\nfont-size: 0.83em !important;\nfont-weight: bold !important;\nline-height: inherit !important;\nmargin:1.67em 0px 1.67em 0px !important;\n}\n.geDiagramContainer h6,\n.drawio-macro h6 {\ncolor: #000 !important;\nfont-size: 0.67em !important;\nfont-weight: bold !important;\nline-height: inherit !important;\nmargin:2.33em 0px 2.33em 0px !important;\n}\nhtml body .geDiagramContainer p,\nhtml body .drawio-macro p {\nmargin: 1em 0 1em 0;\n}";document.getElementsByTagName("head")[0].appendChild(b)}catch(d){}})();
var urlParams=function(b){var d={},f=b.lastIndexOf("?");if(0<f){b=b.substring(f+1).split("\x26");for(var e=0;e<b.length;e++)f=b[e].indexOf("\x3d"),0<f&&(d[b[e].substring(0,f)]=b[e].substring(f+1))}return d}(window.location.href),mxLanguage="undefined"!==typeof LANGUAGE?LANGUAGE:"en";MXGRAPH.mxscriptOnLoad=MXGRAPH.mxscriptOnLoad||{};
function mxscript(b,d){var f=b.substring(b.lastIndexOf("/")+1);if(1==MXGRAPH.mxscriptOnLoad[b]||null!=f&&null!=document.getElementById(f))null!=d&&d();else if(null==MXGRAPH.mxscriptOnLoad[b])if(MXGRAPH.mxscriptOnLoad[b]=[d],"1"!=urlParams.dev){var e=document.createElement("script");e.setAttribute("type","text/javascript");e.setAttribute("defer","true");e.setAttribute("src",b);var g=!1;e.onload=e.onreadystatechange=function(){if(!(g||this.readyState&&"complete"!=this.readyState)){g=!0;for(var h=0;h<
MXGRAPH.mxscriptOnLoad[b].length;h++)if(null!=MXGRAPH.mxscriptOnLoad[b][h])MXGRAPH.mxscriptOnLoad[b][h]();null!=f&&e.setAttribute("id",f);MXGRAPH.mxscriptOnLoad[b]=!0}};d=document.getElementsByTagName("script")[0];null!=d&&d.parentNode.insertBefore(e,d)}else document.write('\x3cscript src\x3d"'+b+'"'+(null!=f?' id\x3d"'+f+'" ':"")+"\x3e\x3c/script\x3e");else MXGRAPH.mxscriptOnLoad[b].push(d)}
mxLoadScripts=function(b,d){for(var f=b.length,e=0;e<b.length;e++)mxscript(b[e],function(){0==--f&&null!=d&&d()})};MXGRAPH.resolvePageTargetName=function(b,d){if(null==b||null==d)return null;d=decodeURIComponent(d);if(-1==d.indexOf("{pageTitle}"))return d;b=8401<=DrawioProperties.buildNumber?b.replace(/-/g,""):b;return d.replace("{pageTitle}",/^[a-zA-Z]/.test(b)?b:"id-"+b).replace(/\s/g,"")};
MXGRAPH.restorePageTitlePlaceholder=function(b,d){if(null==d)return null;b=b.replace(/\s/g,"");return d.replace("id-","").replace(b,"{pageTitle}")};
MXGRAPH.overrideGlobalVariables=function(b,d){d=d||Graph.prototype;var f=d.getGlobalVariable;d.getGlobalVariable=function(e){if(null!=DrawioProperties.serverConfig&&"1"==DrawioProperties.serverConfig.disableplaceholders)return"placeholder disabled";try{if("filename"==e)return b.title||b.diagramDisplayName||b.diagramName;if("creatorName"==e)return b.creatorName;if("lastModifiedBy"==e)return b.lastModifierName;if("lastModifiedTime"==e.substring(0,16)){var g=e.indexOf(":"),h=0<g?e.substring(g+1):"";
return this.formatDate(new Date(b.lastModified),h)}if("version"==e)return b.revision}catch(l){}return f.apply(this,arguments)}};
if("1"==urlParams.dev){var mxDevUrl=document.location.protocol+"//devhost.jgraph.com/drawio/src/main",drawDevUrl=document.location.protocol+"//devhost.jgraph.com/drawio/src/main/webapp/",geBasePath=drawDevUrl+"/js/grapheditor",mxBasePath=mxDevUrl+"/mxgraph";mxscript(drawDevUrl+"js/diagramly/Init.js");mxscript(geBasePath+"/Init.js");mxscript(mxBasePath+"/mxClient.js");mxscript(drawDevUrl+"js/diagramly/Devel.js");mxscript(drawDevUrl+"js/diagramly/GraphViewer.js")}
(function(){function b(){var g=$(".drawio-macro");0<g.length&&(e?f(g):mxscript(ATLAS_RESOURCE_BASE+"/js/atlas-viewer.min.js",function(){mxLoadScripts([ATLAS_RESOURCE_BASE+"/js/EmbedUtils.js",ATLAS_RESOURCE_BASE+"/js/mxViewer.js",ATLAS_RESOURCE_BASE+"/js/DrawioComments.js",ATLAS_RESOURCE_BASE+"/js/shapes-14-6-5.min.js",ATLAS_RESOURCE_BASE+"/js/mxEditorEventListener.js"],function(){e=!0;f(g)})}))}function d(g){if("undefined"===typeof TextDecoder||"undefined"===typeof Uint8Array)return decodeURIComponent(escape(window.atob(g)));
var h=new TextDecoder("utf8"),l=h.decode;g=atob(g);var m=new ArrayBuffer(g.length);m=new Uint8Array(m);for(var k=0;k<g.length;k+=1)m[k]=g.charCodeAt(k);return l.call(h,m.buffer)}function f(g){for(var h=0;h<g.length;h++)try{var l=g[h],m=l.getAttribute("data-macroId"),k=$("#drawio-macro-data-"+m);0<k.length&&(mxConfThemeObserver(function(p,a){a.macro.className=a.className;a.macro.innerHTML="";var n=a.macro;a=a.macroData;var q="drawio-sketch"===n.parentNode.getAttribute("data-macro-name"),c=a.serverConfig;
DrawioProperties={contextPath:AJS.contextPath(),buildNumber:n.getAttribute("data-buildNum"),serverConfig:c};try{a.uiConfig&&(DrawioProperties.uiConfig=JSON.parse(mxUtils.decodeHtml(a.uiConfig)))}catch(r){console.log(r),DrawioProperties.uiConfig={}}c={};a.templateUrl?(c.loadUrl=(0==a.templateUrl.indexOf(AJS.contextPath())?"":AJS.contextPath())+a.templateUrl,c.imageUrl=(0==a.templateImageLoadUrl.indexOf(AJS.contextPath())?"":AJS.contextPath())+a.templateImageLoadUrl):(c.loadUrl=AJS.contextPath()+"/rest/drawio/1.0/diagram/crud/"+
encodeURIComponent(a.diagramName)+"/"+encodeURIComponent(a.owningPageId)+"?revision\x3d"+encodeURIComponent(a.revision),c.imageUrl=AJS.contextPath()+"/download/attachments/"+encodeURIComponent(a.owningPageId)+"/"+encodeURIComponent(a.previewName)+"?version\x3d"+encodeURIComponent(a.revision)+"\x26api\x3dv2",c.editUrl=AJS.contextPath()+"/plugins/drawio/addDiagram.action?ceoId\x3d"+encodeURIComponent(a.ceoId)+"\x26owningPageId\x3d"+encodeURIComponent(a.owningPageId)+"\x26diagramName\x3d"+encodeURIComponent(a.diagramName)+
"\x26revision\x3d"+encodeURIComponent(a.revision)+"\x26diagramDisplayName\x3d"+encodeURIComponent(a.diagramDisplayName)+(q?"\x26ui\x3dsketch\x26saveAndExit\x3d1\x26noSaveBtn\x3d1":"")+(p?"\x26dark\x3d1":""));c.editable=a.editable;c.canComment=a.canComment;c.stylePath=STYLE_PATH;c.stencilPath=STENCIL_PATH;c.imagePath=IMAGE_PATH+"/reader";c.border=a.border;c.width=a.width;c.simpleViewer=a.simpleViewer;c.tbstyle=a.tbstyle;c.links=a.links;c.lightbox=a.lbox;c.resourcePath=ATLAS_RESOURCE_BASE+"/resources/viewer";
c.disableButtons=!1;c.zoomToFit=!0;c.language=a.language;c.licenseStatus=a.licenseStatus;c.contextPath=AJS.contextPath();c.diagramName=a.diagramName;c.diagramDisplayName=a.diagramDisplayName;c.aspect=a.aspect;c.ceoName=a.ceoName;c.attVer=a.revision;c.revision=a.revision;c.attId=a.attId;c.lastModifierName=a.lastModifierName;c.lastModified=parseInt(a.lastModified);c.creatorName=a.creatorName;c.maxScale=parseFloat(a.maxScale);c.extSrvIntegType=a.extSrvIntegType;c.gClientId=a.gClientId;c.oClientId=a.oClientId;
c.service=a.service;c.sFileId=a.sFileId;c.odriveId=a.odriveId;c.diagramUrl=a.diagramUrl;c.csvFileUrl=a.csvFileUrl;c.pageId=a.pageId||Confluence.getContentId();c.aspectHash=a.aspectHash;c.isTemplate=a.isTemplate;""==c.width&&(c.width=null);"GDrive"==a.service||"OneDrive"==a.service||""!=a.diagramUrl||""!=a.csvFileUrl?createRemoteViewer(n,c,null,p):(createViewer(n,c,p),c.editable&&($(n).data("viewerConfig",c),$(n).on("drawioViewerUpdate",updateDrawioViewer)))},{macro:l,className:l.className,macroData:JSON.parse(d(k.text().trim()))}),
k.remove())}catch(p){console.log(p)}setTimeout(b,500)}if("undefined"!==typeof AJS&&!MXGRAPH.macroRenderingStarted){$=AJS.$;MXGRAPH.macroRenderingStarted=!0;var e=!1;$(document).ready(b)}})();
}catch(e){WRMCB(e)};