mxEmbedUtils={sha1:function(b){if(!b)return null;try{var d=require("crypto").createHash("sha1");d.update(b);var c=d.digest("hex")}catch(v){c=void 0}if(void 0!==c)return c;c=function(v,w){return v<<w|v>>>32-w};d=function(v){var w="",x;for(x=7;0<=x;x--){var y=v>>>4*x&15;w+=y.toString(16)}return w};var a,e=Array(80),g=1732584193,q=4023233417,l=2562383102,h=271733878,m=3285377520;b=unescape(encodeURIComponent(b));var f=b.length;var u=[];for(a=0;a<f-3;a+=4){var k=b.charCodeAt(a)<<24|b.charCodeAt(a+1)<<
16|b.charCodeAt(a+2)<<8|b.charCodeAt(a+3);u.push(k)}switch(f%4){case 0:a=2147483648;break;case 1:a=b.charCodeAt(f-1)<<24|8388608;break;case 2:a=b.charCodeAt(f-2)<<24|b.charCodeAt(f-1)<<16|32768;break;case 3:a=b.charCodeAt(f-3)<<24|b.charCodeAt(f-2)<<16|b.charCodeAt(f-1)<<8|128}for(u.push(a);14!==u.length%16;)u.push(0);u.push(f>>>29);u.push(f<<3&4294967295);for(b=0;b<u.length;b+=16){for(a=0;16>a;a++)e[a]=u[b+a];for(a=16;79>=a;a++)e[a]=c(e[a-3]^e[a-8]^e[a-14]^e[a-16],1);k=g;f=q;var n=l;var p=h;var r=
m;for(a=0;19>=a;a++){var t=c(k,5)+(f&n|~f&p)+r+e[a]+1518500249&4294967295;r=p;p=n;n=c(f,30);f=k;k=t}for(a=20;39>=a;a++)t=c(k,5)+(f^n^p)+r+e[a]+1859775393&4294967295,r=p,p=n,n=c(f,30),f=k,k=t;for(a=40;59>=a;a++)t=c(k,5)+(f&n|f&p|n&p)+r+e[a]+2400959708&4294967295,r=p,p=n,n=c(f,30),f=k,k=t;for(a=60;79>=a;a++)t=c(k,5)+(f^n^p)+r+e[a]+3395469782&4294967295,r=p,p=n,n=c(f,30),f=k,k=t;g=g+k&4294967295;q=q+f&4294967295;l=l+n&4294967295;h=h+p&4294967295;m=m+r&4294967295}t=d(g)+d(q)+d(l)+d(h)+d(m);return t.toLowerCase()},
b64toBlob:function(b,d,c,a){d=d||"";c=c||512;b=a?b:atob(b);a=[];for(var e=0;e<b.length;e+=c){for(var g=b.slice(e,e+c),q=Array(g.length),l=0;l<g.length;l++)q[l]=g.charCodeAt(l);g=new Uint8Array(q);a.push(g)}return new Blob(a,{type:d})},saveAtt:function(b,d,c,a,e,g,q,l,h,m){var f=new FormData;d=d instanceof Blob?d:new Blob([d],{type:a});f.append("file",d,c);f.append("minorEdit",!e);c=h?"?status\x3ddraft":"";null!=g&&f.append("comment",g);$.ajax({type:"POST",data:f,url:AJS.contextPath()+"/rest/api/content/"+
encodeURIComponent(b)+"/child/attachment"+(m?"/"+encodeURIComponent(m)+"/data":"")+c,contentType:!1,processData:!1,mimeType:"multipart/form-data",headers:{"X-Atlassian-Token":"nocheck"},success:q,error:l})},getAttachmentsList:function(b,d,c,a){function e(){$.ajax({type:"GET",url:AJS.contextPath()+"/rest/api/content/"+encodeURIComponent(b)+"/child/attachment?start\x3d"+g+"\x26limit\x3d200",contentType:"application/json;charset\x3dUTF-8",success:function(h){for(var m=0;m<h.results.length;m++)a?l[h.results[m].title.toLowerCase()]=
h.results[m]:q.push({id:h.results[m].id,title:h.results[m].title});h._links&&h._links.next?(g+=h.limit,e()):d(a?l:q)},error:c})}var g=0,q=[],l={};e()},getUniqueName:function(b,d){for(var c=d,a=1;b[d.toLowerCase()];)d=a+"-"+c,a++;return d},getViewerAspect:function(b){if(b.diagrams&&b.diagrams[b.currentPage]){var d=[],c=b.diagrams[b.currentPage].getAttribute("id");b=b.graph.getModel();for(var a=b.getChildCount(b.root),e=0;e<a;e++){var g=b.getChildAt(b.root,e);b.isVisible(g)&&d.push(g.id)}return c+" "+
d.join(" ")}return null},getViewImage:function(b,d,c){function a(){d(e)}var e={};c||(e.aspect=mxEmbedUtils.getViewerAspect(b));e.width=Math.round(b.graph.view.graphBounds.width)||null;b.editor.isExportToCanvas()?b.editor.exportToCanvas(function(g){g=g.toDataURL("image/png");e.image=g.substring(g.lastIndexOf(",")+1);d(e)},null,null,null,a):a()},importCsv:function(b,d,c){EditorUi.prototype.createUi=function(){};EditorUi.prototype.addTrees=function(){};EditorUi.prototype.updateActionStates=function(){};
EditorUi.prototype.onBeforeUnload=function(){};var a=new EditorUi;a.handleError=c;a.importCsv(b,function(){var e=a.editor.getGraphXml();d(e,mxUtils.getXml(e))})},initI18nAsync:function(b,d,c){RESOURCE_BASE=(c||AJS.contextPath()+"/download/resources/com.mxgraph.confluence.plugins.diagramly:drawio-editor")+"/resources/dia";mxLanguage=b;mxResources.loadDefaultBundle=!1;b=mxResources.getDefaultBundle(RESOURCE_BASE,b)||mxResources.getSpecialBundle(RESOURCE_BASE,b);mxUtils.getAll([b],function(a){mxResources.parse(a[0].getText());
d&&d()})},applyTranslation:function(b){for(var d=b.querySelectorAll("*[data-i18n]"),c=0;c<d.length;c++){var a=d[c].getAttribute("data-i18n");d[c].innerHTML=mxUtils.htmlEntities(mxResources.get(a,null,d[c].innerHTML))}d=b.querySelectorAll("*[data-i18n-title]");for(c=0;c<d.length;c++)a=d[c].getAttribute("data-i18n-title"),d[c].setAttribute("title",mxUtils.htmlEntities(mxResources.get(a,null,d[c].getAttribute("title"))));b=b.querySelectorAll("*[data-i18n-placeholder]");for(c=0;c<b.length;c++)a=b[c].getAttribute("data-i18n-placeholder"),
b[c].setAttribute("placeholder",mxUtils.htmlEntities(mxResources.get(a,null,b[c].getAttribute("placeholder"))))}};