var gOpenCommentsFn=null;null==window.mxResourcesLoadingDone&&(window.mxResourcesLoadingDone=!1,window.mxMainPending=[]);function gOpenCommentsFunc(){null!=gOpenCommentsFn&&gOpenCommentsFn()}
function mxAddSpinner(c,a){var h=document.createElement("div");h.style.cssText=(a?"position:absolute;top:50%;left:50%;margin-left:-20px;margin-top:-20px;":"position:relative;")+"width:40px;height:40px;";c.appendChild(h);(new Spinner({lines:12,length:7,width:3,radius:6,rotate:0,color:"#000",speed:2,trail:60,shadow:!1,hwaccel:!1,className:"spinner",zIndex:999})).spin(h);return h}
function createViewer(c,a,h){function l(k){c.innerHTML=mxResources.get("error")+": "+mxUtils.htmlEntities(k);c.style.height="24px"}function t(k,p){var b=document.createElement("div");b.style.position="absolute";b.style.overflow="hidden";b.style.left="0px";b.style.top="0px";b.style.right="0px";b.style.fontSize="14px";b.style.margin="2px";mxUtils.setOpacity(b,50);b.style.color="gray";b.style.textAlign="center";b.style.whiteSpace="nowrap";span=document.createElement("span");span.innerHTML=k;b.appendChild(span);
p.appendChild(b)}function u(k){"NO_LICENSE"==a.licenseStatus?t(mxResources.get("drawio.reader.noLicense"),k):"EVAL_LICENSE"==a.licenseStatus?t(mxResources.get("drawio.reader.evaluation"),k):"EVAL_EXPIRED"==a.licenseStatus?t(mxResources.get("drawio.reader.evaluationExpired"),k):"VERSION_MISMATCH"==a.licenseStatus?t(mxResources.get("drawio.reader.versionMismatch",["https://support.draw.io/pages/viewpage.action?pageId\x3d11829320"]),k):"USER_MISMATCH"==a.licenseStatus&&t(mxResources.get("drawio.reader.userMismatch",
["https://support.draw.io/pages/viewpage.action?pageId\x3d11829323"]),k)}function w(k){var p={};try{p=JSON.parse(k)}catch(d){try{mxUtils.parseXml(k);p.xml=k;p.revision="";var b=a.loadUrl.match(/\/([^/]+)$/);p.name=2<=b.length?decodeURIComponent(b[1]):""}catch(f){}}return p}function A(k,p){if(null!=k){var b=k.openLink;k.openLink=function(f,g){var n=window,e=f;f=f.replace(/\+/g,"%2B");e.substring(0,this.baseUrl.length)==this.baseUrl&&"#"==e.charAt(this.baseUrl.length)&&"_top"==g&&window==window.top?
(e=document.createElement("a"),e.href="#"+MXGRAPH.resolvePageTargetName(p,f.split("#")[1]),e.style.display="none",c.appendChild(e),e.click(),e.parentNode.removeChild(e)):n=-1!=f.lastIndexOf("/lightbox.action")?b.apply(this,[f,"_blank"]):b.apply(this,arguments);return n};var d=k.customLinkClicked;k.customLinkClicked=function(f){var g=AJS.contextPath();if("data:confluence/id,"==f.substring(0,19)){var n=f.substring(19),e=window.open();if(n)$.ajax({url:g+"/rest/api/content/"+encodeURIComponent(n),type:"GET",
success:function(v){e.location=document.location.origin+g+v._links.webui},error:function(){e.document.writeln(mxResources.get("objectNotFound"))}});else throw Error("Empty ID");}else if("data:scrollPage,"==f.substring(0,16))try{var q=JSON.parse(Base64.decode(f.substring(16)));e=window.open();e.document.writeln(mxResources.get("connecting")+"...");$.ajax({url:g+"/rest/api/content/"+encodeURIComponent(AJS.Confluence.getContentId()),type:"GET",success:function(v){var r=v.space.key;if(/^[ -~\t\n\r]+$/.test(q.confTitle)){var x=
document.location.origin+g+"/display/"+encodeURIComponent(r)+"/"+encodeURIComponent(q.confTitle.replace(/\s/g,"+"));$.ajax({url:x,type:"GET",success:function(C){e.location=x},error:function(C){$.ajax({url:g+"/rest/api/content/"+encodeURIComponent(q.confId),type:"GET",success:function(E){e.location=document.location.origin+g+"/display/"+encodeURIComponent(r)+"/"+encodeURIComponent(E.title.replace(/\s/g,"+"))},error:function(E){e.document.writeln(mxResources.get("pageNotFound"))}})}})}else e.location=
document.location.origin+g+"/pages/viewpage.action?pageId\x3d"+encodeURIComponent(q.confId)},error:function(){e.document.writeln(mxResources.get("pageNotFound"))}});return!0}catch(v){throw Error("Unexpected Error");}else return d.apply(this,arguments)}}}function D(k,p){null!=k&&null!=p&&$(k).parents().each(function(b,d){"ui-expand"==$(d).data("macro-name")&&(p["check-visible-state"]=!1)})}if(null!=c){var B=$.Deferred(),F=!1,m=c.parentNode;null==m||null==m.previousSibling||"drawio"!=m.getAttribute("data-macro-name")||
"P"!=m.previousSibling.nodeName||0!=m.previousSibling.childNodes.length&&""!=m.previousSibling.innerHTML.trim()||m.previousSibling.appendChild(c);try{a.darkMode=h;var G=a.contextPath;editUrl=a.editUrl;Editor.initMath();GraphViewer.initCss();"undefined"!==typeof DrawioProperties&&DrawioProperties.uiConfig&&DrawioProperties.uiConfig.fontCss&&Editor.configureFontCss(DrawioProperties.uiConfig.fontCss);a.isTemplate&&(GraphViewer.prototype.checkVisibleState=!1);if(!window.mxResourcesLoaded&&null!=a.language){window.mxResourcesLoaded=
!0;var K=a.language;mxResources.isLanguageSupported(K)&&(mxClient.language=K);mxUtils.getAll([mxResources.getSpecialBundle(RESOURCE_BASE,mxClient.language)||mxResources.getDefaultBundle(RESOURCE_BASE,mxClient.language),a.resourcePath+("de"==K?"_de":"")+".txt"],function(b){for(var d=0;d<b.length;d++)mxResources.parse(b[d].getText());for(window.mxResourcesLoadingDone=!0;0<window.mxMainPending.length;)window.mxMainPending.pop()()});var L=document.head.getElementsByTagName("link"),H=null;for(m=0;m<L.length;m++){var I=
L[m];if("text/css"===I.getAttribute("type")&&"stylesheet"===I.getAttribute("rel")&&/.*\/styles\/custom\.css\?spaceKey=.*$/.test(I.getAttribute("href"))){H=I.outerHTML;break}}if(null!=H){var O=PrintDialog.createPrintPreview;PrintDialog.createPrintPreview=function(){var b=O.apply(this,arguments),d=b.writeHead;b.writeHead=function(f){d.apply(this,arguments);null!=H&&f.writeln(H)};return b}}}function k(b){if("undefined"!==typeof DrawioProperties&&DrawioProperties.serverConfig&&DrawioProperties.serverConfig.linkAdjustments){if("string"===
typeof DrawioProperties.serverConfig.linkAdjustments)try{for(var d=JSON.parse(mxUtils.decodeHtml(DrawioProperties.serverConfig.linkAdjustments)),f=0;f<d.length;f++)d[f].re=new RegExp(d[f].re,d[f].m);DrawioProperties.serverConfig.linkAdjustments=d}catch(n){console.log("linkAdjustments parsing error",n)}try{if("object"===typeof DrawioProperties.serverConfig.linkAdjustments)for(d=DrawioProperties.serverConfig.linkAdjustments,f=0;f<d.length;f++){var g=d[f];b=b.replace(g.re,g.r)}}catch(n){console.log("linkAdjustments error",
n)}}return b}var P=Graph.prototype.getAbsoluteUrl;Graph.prototype.getAbsoluteUrl=function(b){null!=b&&(b=k(b),"/"==b.charAt(0)&&b.substring(0,G.length)!==G&&(b=G+b));return P.apply(this,arguments)};var Q=Graph.prototype.getTooltipForCell;Graph.prototype.getTooltipForCell=function(b){var d=null;try{return mxUtils.isNode(b.value)&&(d=b.value.getAttribute("link"),null!=d&&b.value.setAttribute("link",k(d))),Q.apply(this,arguments)}finally{null!=d&&b.value.setAttribute("link",d)}};GraphViewer.prototype.toolbarZIndex=
1;var R=GraphViewer.prototype.getImageUrl,S=/^(\.\.\/)*(\.\.)?\/download\//,M=/.*com.mxgraph.confluence.plugins.diagramly:(drawio|diagramly)-editor/;GraphViewer.prototype.imageBaseUrl=document.location.origin+"/";GraphViewer.prototype.getImageUrl=function(b){return null==b?b:"img/"==b.substring(0,4)?-1!=b.indexOf(".svg")?SVGLOADER_URL+"?url\x3d"+encodeURIComponent(b):ATLAS_RESOURCE_BASE+"/"+b:"/img/"==b.substring(0,5)?ATLAS_RESOURCE_BASE+b:S.test(b)?G+b.substring(b.indexOf("/download/")):"data:image"!=
b.substring(0,10)&&M.test(b)?ATLAS_RESOURCE_BASE+b.replace(M,""):-1!=b.indexOf("/drawio/1.0/diagram/getImageAtt")?b:R.apply(this,arguments)};var T=GraphViewer.prototype.addClickHandler;GraphViewer.prototype.addClickHandler=function(b,d){var f=mxUtils.bind(this,function(){var g=b.container.getElementsByTagName("img");if(null!=g)for(var n=0;n<g.length;n++)g[n].setAttribute("src",this.getImageUrl(g[n].getAttribute("src")))});b.model.addListener(mxEvent.CHANGE,f);f();T.apply(this,arguments)};GraphViewer.prototype.showLightbox=
function(b,d,f){this.showLocalLightbox()};null!=a.width&&"fixed"!=a.width&&(c.style.width=a.width+"px");function p(b,d){if(!d&&!window.mxResourcesLoadingDone)window.mxMainPending.push(function(g){p(b,g)});else if(!F){F=!0;GraphViewer.prototype.autoCrop=!0;var f=mxAddSpinner(c);mxUtils.get(a.loadUrl,mxUtils.bind(this,function(g){try{f.parentNode.removeChild(f)}catch(C){console.log("drawio: viewer noise",C)}c.style.minHeight="";if(200>g.getStatus()||299<g.getStatus())l(g.getStatus());else{mxStencilRegistry.dynamicLoading=
!0;u(c);g=w(g.getText());var n=mxUtils.parseXml(g.xml);a.border&&(c.style.border="1px solid #d0d0d0");var e={"toolbar-position":a.tbstyle,nav:!0,highlight:"#3b73af",border:8,"dark-mode":h};"auto"!=a.links&&(e.target=a.links);"top"==a.tbstyle&&(e.title=(null!=a.diagramDisplayName&&0<a.diagramDisplayName.length?a.diagramDisplayName:g.name)+" ["+g.revision+"]");a.lightbox||(e.lightbox=!1);"hidden"==a.tbstyle?e.resize=!0:(e.toolbar="edit pages zoom layers tags",a.lightbox&&(e.toolbar+=" lightbox"));"fixed"==
a.width?(c.style.maxWidth="",e["allow-zoom-out"]=!1):null!=a.width&&(e["allow-zoom-in"]=!0);e.zoom=isFinite(a.maxScale)?a.maxScale:1;var q=null;e["toolbar-buttons"]={edit:{title:mxResources.get("edit"),enabled:a.editable,image:MXGRAPH.editImage,handler:function(y){-1==a.editUrl.lastIndexOf("page-id")&&(a.editUrl=a.editUrl+"\x26page\x3d"+r.currentPage);a.editUrl+="\x26directEdit\x3dtrue";MXGRAPH.openEditor(a.editUrl,y.srcElement);MXGRAPH.viewerContainer=c;MXGRAPH.readerOpts=a}}};if(null!=a.aspect&&
0<a.aspect.length&&(pageAndLayers=a.aspect.split(" "),e.layerIds=1<pageAndLayers.length?pageAndLayers.slice(1):null,pageId=pageAndLayers[0],a.editUrl+="\x26page-id\x3d"+pageId,diagrams=n.documentElement.getElementsByTagName("diagram"),null!=diagrams))for(var v=0;v<diagrams.length;v++)if(diagrams[v].getAttribute("id")==pageId){e.page=v;break}MXGRAPH.overrideGlobalVariables(a);D(c,e);var r=new GraphViewer(c,n.documentElement,e);function C(){A(r.graph,a.ceoName);MXGRAPH.overrideCellTooltips(r.graph,
a.ceoName)}r.addListener("render",C);C();MXGRAPH.addCommentsIcon(r,c,g.attachmentId);var x=null;EditorUi.prototype.createUi=function(){};EditorUi.prototype.addTrees=function(){};EditorUi.prototype.updateActionStates=function(){};EditorUi.prototype.installNativeClipboardHandler=function(){};EditorUi.prototype.createKeyHandler=function(){var y=new mxKeyHandler(this.editor.graph);y.bindAction=function(){};return y};EditorUi.prototype.getServiceName=function(){return"atlassian"};function E(){null==x&&
(x=new EditorUi(new Editor(!1,null,null,null,!1)),x.editor.attachmentInfo={attachmentId:a.attId,revision:a.attVer},x.canComment=function(){return a.canComment});return x}function N(){null!=q?q.window.setVisible(!q.window.isVisible()):(q=new CommentsWindow(E(),document.body.offsetWidth-380,120,300,350),q.window.setVisible(!0),q.window.getElement().style.position="fixed");q.window.getElement().style.zIndex=2E3}a.canComment&&(EditorUi.prototype.lightboxToolbarActions=[{icon:Editor.commentImage,tooltip:mxResources.get("comments"),
fn:gOpenCommentsFunc}]);null!=r.graph&&null!=r.graph.model&&(r.showLocalLightbox=function(y){gOpenCommentsFn=N;var J=GraphViewer.prototype.showLocalLightbox.call(r);A(J.editor.graph,a.ceoName);var U=J.destroy;J.destroy=function(){null!=q&&q.window.setVisible(!1);U.apply(this,arguments)};y&&N();return J},a.canComment&&E().hasUnresolvedComments(function(y){y&&(img=document.getElementById("comments-icon-"+a.attId),img.style.display="inline")},function(){}),b.resolve(r))}}),function(){f.parentNode.removeChild(f);
c.style.minHeight="";l(req.getStatus())})}}if(a.simpleViewer){var z=document.createElement("img");z.setAttribute("src",a.imageUrl);z.setAttribute("border","0");z.style.cssText="width:100%;box-sizing:border-box;padding:8px;";"fixed"==a.width&&(c.style.overflow="visible",z.style.width="");a.border&&(z.style.border="1px solid #d0d0d0");c.appendChild(z);a.lightbox&&(z.style.cursor="pointer",mxEvent.addListener(z,"click",function(){var b=mxAddSpinner(c,!0);mxUtils.get(a.loadUrl,function(d){b.parentNode.removeChild(b);
200<=d.getStatus()&&299>=d.getStatus()&&(d=w(d.getText()),d=mxUtils.parseXml(d.xml),d=new GraphViewer(null,d.documentElement,{highlight:"#3b73af",nav:!0,lightbox:!1,toolbar:"pages zoom layers tags",target:a.links,"check-visible-state":!1}),A(d.showLocalLightbox().editor.graph,a.ceoName))},function(){b.parentNode.removeChild(b)})}))}else c.style.minHeight="200px",p(B),setTimeout(function(){for(;0<window.mxMainPending.length;)window.mxMainPending.pop()(!0)},2E3)}catch(k){l(k.message)}return B.promise()}}
MXGRAPH.addCommentsIcon=function(c,a,h){var l=document.createElement("img");l.style.cssText="position:absolute;bottom: 5px; right: 5px;opacity: 0.25; cursor: pointer;display : none";l.id="comments-icon-"+h;l.setAttribute("title",mxResources.get("showComments"));l.src=Editor.commentImage;l.addEventListener("click",mxUtils.bind(this,function(){c.showLocalLightbox(!0)}));a.appendChild(l)};
function updateDrawioViewer(c,a,h){viewerConfig=$(this).data("viewerConfig");a==viewerConfig.diagramName&&($(this).empty(),viewerConfig.editUrl=viewerConfig.editUrl.replace(/revision=\d+/,"revision\x3d"+h),viewerConfig.loadUrl=viewerConfig.loadUrl.replace(/revision=\d+/,"revision\x3d"+h),viewerConfig.attVer=h,createViewer(this,viewerConfig,viewerConfig.darkMode))}
MXGRAPH.openEditor=function(c,a){var h=$('\x3ciframe id\x3d"drawioEditor" \x3e');h.appendTo("body");h.css({position:"fixed",width:"100%",height:"100%",top:"0px",left:"0px","border-style":"none",zIndex:9E3});h.attr("src",c);MXGRAPH.editorFrame=h;MXGRAPH.editImgEl=a;a.src=window.IMAGE_PATH+"/spin.gif";a.width=21;a.height=21};
MXGRAPH.closeEditor=function(){MXGRAPH.editorFrame.remove();MXGRAPH.editorFrame=null;MXGRAPH.viewerContainer=null;MXGRAPH.readerOpts=null;document.body.style.overflow="auto";MXGRAPH.editImgEl.src=MXGRAPH.editImage};
MXGRAPH.postSave=function(c,a,h,l){$(".drawio-macro").trigger("drawioViewerUpdate",[a,h]);c=new mxXmlRequest(AJS.contextPath()+"/rest/drawio/1.0/diagram/updateMacros/"+c+"/"+encodeURIComponent(a)+"/"+h+"?diagramWidth\x3d"+l,"","POST");c.setRequestHeaders=function(t,u){t.setRequestHeader("X-Atlassian-Token","no-check")};c.send(function(t){},function(t){console.log("There was a problem updating the drawio macro")})};
MXGRAPH.overrideCellTooltips=function(c,a){null!=c&&(oldF=c.getTooltipForCell,c.getTooltipForCell=function(h){var l=oldF.apply(this,arguments);return null!=h.value&&null!=h.value.getAttribute&&null!=h.value.getAttribute("tooltip")?l:null==l?null:MXGRAPH.resolvePageTargetName(a,l)})};
function createRemoteViewer(c,a,h,l){var t="localhost"==window.location.hostname?"test.draw.io":"ac.draw.io",u=AJS.Meta.get("user-locale");if(null!=u){var w=u.indexOf("_");0<=w&&(u=u.substring(0,w))}if(null!=c){c.style.height="200px";c.style.width="100%";w=a.diagramUrl||a.csvFileUrl?"extUrl":"GDrive"==a.service?"gdrive":"onedrive";var A="";if(l){var D=document.createElement("div");D.style.color="var(--ds-surface)";document.body.appendChild(D);A="\x26dark\x3d1\x26bkgrndClr\x3d"+encodeURIComponent(getComputedStyle(D).color);
a.darkMode=l;document.body.removeChild(D)}l=3==a.extSrvIntegType||a.diagramUrl||a.csvFileUrl?AJS.contextPath()+"/plugins/drawio/embedViewer.action?type\x3d"+w+"\x26lang\x3d"+u+A:"https://"+t+"/connect/remote_"+w+"/viewer.html?lang\x3d"+u+A;l=$('\x3ciframe style\x3d"height:100%;width:100%;border:0" src\x3d"'+l+'"\x3e');$(c).append(l);var B=l[0].contentWindow,F=mxAddSpinner(c);window.addEventListener("message",function(m){if(m.source==B)switch(m=JSON.parse(m.data),m.action){case "viewerReady":B.postMessage(JSON.stringify({action:"viewFile",
data:a}),"*");F.parentNode.removeChild(F);break;case "diagramRendered":null!=h&&(a.fileTS=m.fileTS,h(a,B));break;case "updateHeight":c.style.height=m.height+"px"}});return B}}MXGRAPH.editImage="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVBAMAAABbObilAAAAD1BMVEUAAAAAAAAQEBBycnIgICBqwj3hAAAAAXRSTlMAQObYZgAAADlJREFUCNdjoBwoChrAmCyGggJwYWVBBSiTSVDICKFa0AEuLCiEJKyAX5gBSZgBSZgBKGwMBKQ7HAAWzQSfKKAyBgAAAABJRU5ErkJggg\x3d\x3d";